
run: main
	java Main
	make clean

main: Main.java MyMenu.java SelectionState.java TextEditor.java TextEditorModel.java UndoManager.java ClipboardStack.java StatusBar.java
	javac Main.java


clean:
	rm *.class