


all: zadatak2 zadatak1

zadatak1: zadatak1-moveShapes.cpp zadatak1-solved.cpp
	g++ -o moveShapes.exe zadatak1-moveShapes.cpp
	g++ -o solved1.exe zadatak1-solved.cpp


zadatak2: zadatak2-mymax.cpp
	g++ -o solved2.exe zadatak2-mymax.cpp

